disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Panagiotis Englezos"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Panagiotis Englezos also known as penglezos is a Full-stack and Android developer from Greece."
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Panagiotis Englezos"
  email = "panagiotisegl@gmail.com"
  image = "img/logo.webp"
  imageQuality = 96
  headline = "Full-stack & Android developer"
  bio = "Full-stack & Android developer"
  links = [
    { github = "https://github.com/penglezos" },
    { linkedin = "https://linkedin.com/in/penglezos" },
    { email = "mailto:panagiotisegl@gmail.com" },
  ]