baseURL = "http://penglezos.dev/"
languageCode = "en-us"
title = "penglezos"
theme = "PaperMod"

[params.profileMode]
enabled = true
title = "Panagiotis Englezos"
subtitle = "Software & Web developer"
imageUrl = "https://avatars.githubusercontent.com/u/7030531"
imageTitle = "Panagiotis Englezos"
imageWidth = 160

[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/penglezos"

[[params.socialIcons]]
name = "Linkedin"
url = "https://linkedin.com/in/penglezos"

[[params.socialIcons]]
name = "Email"
url = "mailto:panagiotisegl@gmail.com"
