baseURL = "http://penglezos.dev/"
languageCode = "en-us"
title = "penglezos"
theme = "PaperMod"

[params]
  description = "penglezos software and web developer"
  author = "penglezos"

[params.profileMode]
  enabled = true
  title = "Panagiotis Englezos"
  subtitle = "Software & Web developer"
  imageUrl = "images/logo.webp"
  imageTitle = "Panagiotis Englezos"
  imageWidth = 160
  imageHeight = 150

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 10

[[params.socialIcons]]
  name = "Github"
  url = "https://github.com/penglezos"

[[params.socialIcons]]
  name = "Linkedin"
  url = "https://linkedin.com/in/penglezos"

[[params.socialIcons]]
  name = "Email"
  url = "mailto:panagiotisegl@gmail.com"
