baseURL = "http://penglezos.dev/"
languageCode = "en-us"
title = "penglezos"
theme = "PaperMod"

[params.profileMode]
enabled = true
title = "Panagiotis Englezos"
subtitle = "Software & Web developer"
description = "penglezo's personal website."
keywords = "penglezos, panagiotis englezos, panagiotisenglezos"
imageUrl = "images/logo.png"
imageTitle = "Panagiotis Englezos"
imageWidth = 160

[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/penglezos"

[[params.socialIcons]]
name = "Linkedin"
url = "https://linkedin.com/in/penglezos"

[[params.socialIcons]]
name = "Email"
url = "mailto:panagiotisegl@gmail.com"
