baseURL = "http://penglezos.dev/"
languageCode = "en-us"
title = "penglezos"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  description = "penglezos software and web developer"
  author = "penglezos"
  keywords = ['penglezos', 'panagiotisenglezos', 'panagiotis englezos']

[params.profileMode]
  enabled = true
  title = "Panagiotis Englezos"
  subtitle = "Full-stack & Android developer"
  imageUrl = "images/logo.webp"
  imageTitle = "Panagiotis Englezos"
  imageWidth = 160
  imageHeight = 150

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 5

[[params.socialIcons]]
  name = "Github"
  url = "https://github.com/penglezos"

[[params.socialIcons]]
  name = "Linkedin"
  url = "https://linkedin.com/in/penglezos"

[[params.socialIcons]]
  name = "Email"
  url = "mailto:panagiotisegl@gmail.com"

[[params.socialIcons]]
  name = "Telegram"
  url = "https://t.me/penglezos"
