baseURL = 'http://penglezos.github.io'
languageCode = 'en-us'
title = 'Panagiotis Englezos'
theme = 'hello-friend-ng'

[author]
  name = "Panagiotis Englezos"

[languages]
  [languages.en]
    keywords = ""
    title = "Panagiotis Englezos"
    homeSubtitle = "..."
    readOtherPosts = "Read other posts"

[languages.en.params.logo]
    logoHomeLink = "/"
    logoText = "penglezos"